### ISSUE TITLE
Implement __copy__ and/or __deepcopy__ to allow settrie cloning

### ISSUE THREAD

**Issue by ldeluigi** [BBVA/mercury-settrie#12]
https://docs.python.org/3/library/copy.html

**Comment by sbasaldua** [comment]
(See https://github.com/BBVA/mercury-settrie/blob/features/towards_146/CHANGELOG.md for state updates.)

Copying the state of the internal object (which is stored in many stlib containers) when you save the Python object was the first feature request this library had before it was OSS. Luckily, it is implemented and the state gets serialized as a list of base64-encoded Python strings. If you look at the methods `save_as_binary_image()` and `load_from_binary_image()`, you can see how it is done.

So this implementation boils down to a pure-Python implementation of the __copy__() method.

If you think you can do it, I would be more than happy to have you as a collaborator and push to the `features/towards_146` branch. Otherwise, I can do that when I am done with the other issues.

**Comment by ldeluigi** [comment]
Great! Will do
