### ISSUE TITLE
SetTrie.supersets doesn't work if passing the empty set as argument

### ISSUE THREAD

**Issue by ldeluigi** [BBVA/mercury-settrie#14]
`self._sets.supersets(set())` should return all the sets in the SeTrie if any, but instead, it returns always an empty result

**Comment by sbasaldua** [comment]
(See https://github.com/BBVA/mercury-settrie/blob/features/towards_146/CHANGELOG.md for state updates.)

You are right on this one. The empty set has always been a special case that is detected rather than handled by the main algorithm. The consistent output in this case is the list of all sets. It is straightforward, I will change it.

**Comment by sbasaldua** [comment]
Fixed in version 1.4.6
