### ISSUE TITLE
SetTrie should handle frozensets just like sets

### ISSUE THREAD

**Issue by ldeluigi** [BBVA/mercury-settrie#15]
In Python, a set of sets can't be built. It's common for developers to use frozensets instead of sets where possible, so that they can be hashed and put inside sets and other frozensets freely.

SetTrie is a set of sets, so a Python developer wouldn't expect it to run fine with sets, but it does. Nevertheless, it should work with frozenset, much like a python set would do.

https://docs.python.org/3/library/stdtypes.html#frozenset

**Comment by sbasaldua** [comment]
(See https://github.com/BBVA/mercury-settrie/blob/features/towards_146/CHANGELOG.md for state updates.)

I give you a little bit of detail on how SetTrie.insert() works: It does not understand Python's internal and does not understand sets, it understands how Python serializes sets as strings. If you have `a = {'1', 2.0, 3}` the Python object will call the c++ object with the string `"{2.0, 3, '1'}"` and that is what the c++ implementation breaks down into `2.0`, `3` and `'1'` all of which are strings (represented by their binary hashes) for the c++ implementation. When you enumerate the elements, they are sent "as is" to the Python object which identifies the bounding '' and converts back to str(), and the dot makes it a float, otherwise an int.

Now, when you give it a frozenset, `str(frozenset(a))` returns `"frozenset({2.0, 3, '1'})"` and that is something the c++ implementation cannot parse. Would it be enough to make the parser silently ignore the frozenset parts and serialize and insert the rest? That would completely forget that the source of the set was a frozenset and everything would work just as if you gave it a set. What do you think?

**Comment by ldeluigi** [comment]
It's fine, but I'd suggest putting a guard written in python before inserting incompatible stuff in the data structure.
Something like:
```python
def insert(self, aset: Set, id: str):
        """ Inserts a new set into a SetTrie object.

        Args:
            set: Set to add
            id: String representing the ID for the test
        """
        self.int_ids = None
        if not isinstance(aset, set) or not isinstance(aset, frozenset):
             raise ValueError("The first argument must be a set or a frozenset")
        insert(self.st_id, str(set), id)
```

Additionally, I'd guard against insertion of stuff that is not int, float or string, to prevent errors at a later stage:

```python
    def insert(self, aset: Set, id: str):
        """ Inserts a new set into a SetTrie object.

        Args:
            set: Set to add
            id: String representing the ID for the test
        """
        if not isinstance(aset, set) or not isinstance(aset, frozenset):
            raise ValueError("The first argument must be a set or a frozenset")
        for e in aset:
            if not isinstance(e, int) and not isinstance(e, float) and not isinstance(e, str):
                raise ValueError(f"The elements of the set must be integers, floats or strings. Found {type(e)}")
        self.int_ids = None
        insert(self.st_id, str(set), id)
```

And finally, at that point you can solve the frozenset case by customizing the string representation passed down to c++:
```python
    def insert(self, aset: Set, id: str):
        """ Inserts a new set into a SetTrie object.

        Args:
            set: Set to add
            id: String representing the ID for the test
        """
        if not isinstance(aset, set) or not isinstance(aset, frozenset):
            raise ValueError("The first argument must be a set or a frozenset")
        for e in aset:
            if not isinstance(e, int) and not isinstance(e, float) and not isinstance(e, str):
                raise ValueError(f"The elements of the set must be integers, floats or strings. Found {type(e)}")
        self.int_ids = None
        insert(self.st_id, '{' + ','.join(map(str, aset)) + '}', id)
```

**Comment by sbasaldua** [comment]
Hi ldeluigi,

All 5 issues are now implemented on branch `features/towards_146`.

On the type checking logic, I think passing a well formed string (like a row of a csv file) can also be an interesting option. I prefer not to add overhead to functions that are possibly called millions of times. On a given application, the type passed will probably always be the same.

The forzensets support applies to insert(), find(), subsets() and supersets() and there is no function that returns sets (just elements in the iterator) so the implementation is more consistent than what I initially thought. What do you think?

If you have any comments, please answer any of the issues. Otherwise, I will merge and publish version 1.4.6 as it is in the branch tomorrow.

Thanks again for your contributions!

**Comment by ldeluigi** [comment]
> Hi ldeluigi,
> 
> All 5 issues are now implemented on branch `features/towards_146`.
> 
> On the type checking logic, I think passing a well formed string (like a row of a csv file) can also be an interesting option. I prefer not to add overhead to functions that are possibly called millions of times. On a given application, the type passed will probably always be the same.
> 
> The forzensets support applies to insert(), find(), subsets() and supersets() and there is no function that returns sets (just elements in the iterator) so the implementation is more consistent than what I initially thought. What do you think?
> 
> If you have any comments, please answer any of the issues. Otherwise, I will merge and publish version 1.4.6 as it is in the branch tomorrow.
> 
> Thanks again for your contributions!

https://github.com/BBVA/mercury-settrie/blob/ecfde4dad000c20ae505217f7b1e6e60356e884d/src/settrie/settrie.cpp#L764

Shouldn't be checked that size of string is > than 9 before accesssing the tenth character? In the preceding line I only see a check for size > 4.

Additionally, are we sure that taking the size of the string using strlen is fine with all the possible unicode characters that I can put in python strings? I don't remember if the encoding was compatible but maybe it is.

**Comment by sbasaldua** [comment]
Oops. Good catch! Fixed.

**Comment by sbasaldua** [comment]
UTF encoding is supported and even part of the tests. We frequently use Spanish words with "ñ", "á", ... as elements. The keyword "frozenset()" is just plain vanilla ASCII.

**Comment by ldeluigi** [comment]
Looks good to me then!

**Comment by sbasaldua** [comment]
I pushed the next version. This closes all the open issues.

Thank you again for your contribution.
