### ISSUE TITLE
CI Workflow for running tests at each commit/PR

### ISSUE THREAD

**Issue by ldeluigi** [BBVA/mercury-settrie#17]
I'd suggest to setup a [GitHub Actions](https://docs.github.com/en/actions/using-workflows/about-workflows) workflow to run tests at every commit and before any release

**Comment by sbasaldua** [comment]
Hi. We do use github actions for pushing the documentation and the package to PYPI. To develop and test, you can use the `mercury-settrie/src` folder as the project root. It has a makefile. You can run everything from the console or configure VS Code so that you can debug both the c++ and the python code without leaving the IDE. That is good enough for me.

Content of VS Code launch.json:

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Python Debugger: Current File",
			"type": "debugpy",
			"request": "launch",
			"program": "${file}",
			"console": "integratedTerminal"
		},
		{
			"name": "(gdb) test",
			"type": "cppdbg",
			"request": "launch",
			"program": "${workspaceFolder}/settrie_test",
			"args": [],
			"stopAtEntry": false,
			"cwd": "${workspaceFolder}",
			"environment": [],
			"MIMode": "gdb",
			"setupCommands": [
				{
					"description": "Enable pretty-printing for gdb",
					"text": "-enable-pretty-printing",
					"ignoreFailures": true
				}
			]
		}
	]
}
```

**Comment by ldeluigi** [comment]
I think you can safely track the launch.json with git, it would help people get started for contributing

**Comment by ldeluigi** [comment]
The CI for test comes in handy to ensure PRs make them pass without having to clone them

**Comment by sbasaldua** [comment]
A local makefile works well enough for this small project with a single maintainer, we can revisit automation if the project complexity or team size grows. I will add the launch.json as you suggested.
